### ISSUE TITLE
On Linux, uiua pad breaks with keyboards set to use dead keys

### ISSUE THREAD

**Issue by JobLeonard** [uiua-lang/uiua#91] opened 2023-10-06 12:13 UTC
https://github.com/uiua-lang/uiua/assets/259840/543360d6-e4e0-451d-81e7-9c08c3af576e

I have my keyboard set to US International with "dead keys", so that I can type out characters with accents and whatnot. Basically, when I hit `"`, `^`, `´`, `~` or backtick they are initially modifiers for the next input, and aren't their own symbols until I press space. In some cases, like `"`, pressing it twice results in a different symbol (`¨`).

This actually breaks on *quite* a few web-apps these days (after working just fine for years), so it's not a unique problem to the uiua pad. So "hopefully" this is limited to me and my Linux set-up and nobody else has to deal with it.

**Comment by kaikalii** [comment] 2023-10-07 06:38
I've actually experienced this on mobile Firefox.
I'm not sure if it's necessarily unique to your setup.
The problem is mobile Firefox doesn't have debug mode, so I'm not sure how to figure out the problem.
If you have a way to reproduce this on Windows, I'd love to take a look.

**Comment by kaikalii** [comment] 2024-03-09 06:48
Both the pad and mobile Firefox have improved over the pad few months.
I think this should be fixed.

**Closed by kaikalii** 2024-03-09 06:48 UTC
Labels: bug
