### ISSUE TITLE
selecting text with double click broken in Pad in Firefox

### ISSUE THREAD

**Issue by TeddyDD** [uiua-lang/uiua#128] opened 2023-10-13 17:35 UTC
Selection randomly picks parts of text, different to text selected by the user. It breaks copying too.

https://github.com/uiua-lang/uiua/assets/4397533/e708b779-e084-4215-bae8-145a70625a5a

Mozilla Firefox 118.0.1

Console output (noting interesting but for the sake of completeness): 

```
downloadable font: Glyph bbox was incorrect (glyph ids 335 482 558 858 869 875 888 1169 1226 1229 1237 1254 1272 1379 1388 1389 1414 1424 1467 1574 1577 1580 1581 1582 1583 1584 1585 1590 1592 1594 1595 1598 1600 1609 1614 1616 1619 1620 1625 1627 1630 1633 1634 1635 1638 1639 1643 1646 1647 1650 1658 1662 1668 1670 1680 1683 1687 1689 1694 1701 1702 1708 1710 1712 1718 2039 2041 2240 2261 2957 2983 3013 3983 3997 4163 4164 4603 4604 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 4618 4619 4620 4621 4622 4623 4625 4626 4627 4628 4629 4630 4631 4632 4633 4636 4637 4638 4639 4640 4868 4869 4923 4931 4979 4982 4990 4993 4994 5000 5001 5003 5009 5014 5029 5030 5031 5032 5033 5300 5332 5336 5352 5939 5942 5945) (font-family: "Main Font" style:normal weight:400 stretch:100 src index:0) source: https://www.uiua.org/DejaVuSans.ttf
```

**Comment by kaikalii** [comment] 2023-10-13 18:01
I'm aware there are some weird bugs.
Unfortunately, `contenteditable` `<div>`s are very hard to make work correctly, especially if you are trying to add dynamic styling the the Uiua editor does.
I'll to my best to fix this.

**Comment by kaikalii** [comment] 2023-10-13 20:56
So, I looked into fixing this, and I'm really not sure how.
I tried making the checking for the where the cursor is more defensive against weird states, to no avail.
It seems to work in Chrome, but not Firefox.
It should be noted that this bug *doesn't* exist in BQNPad, so it should be possible.
I'd welcome help.

**Comment by iFreilicht** [comment] 2023-10-14 14:02
I use uiua pad in Firefox 118.0.2 and am unable to reproduce this issue at all. Every action you show in the video works 100% as expected on my machine. Could this be related to some extension you have installed? Or might it be related to the OS+Firefox combination? I am on macOS.

**Comment by kaikalii** [comment] 2023-10-14 16:29
To break it, you have to select a line by *double clicking* it.
Selection via dragging the mouse and selection with shift+arrows works fine.

**Comment by iFreilicht** [comment] 2023-10-14 20:12
Double clicking doesn't break it for me, only triple clicking, but ok, now I see the issue 😬

**Comment by TeddyDD** [comment] 2023-10-14 22:25
> Could this be related to some extension you have installed? Or might it be related to the OS+Firefox combination?

I created new profile to test it. OS is more likely - I tested this on Linux.

**Comment by goyalyashpal** [comment] 2023-10-15 15:28
I faced a similar issue on android:

* vivaldi browser: 5.6.2868.29
* os: Android 12

https://github.com/uiua-lang/uiua/assets/19423063/3e98425e-0977-415a-8cc6-d9c2a29bb1f2

----

There was one more issue: the editor area was suuuper jumpy, it was so hard to make this selection. Above video is trimmed off from this complete video below 👇 :

https://github.com/uiua-lang/uiua/assets/19423063/aa056052-fd6a-4076-a6f2-d8a6ff1fb2ab

**Comment by kaikalii** [comment] 2024-07-06 22:55
Should have been fixed with new pad

**Closed by kaikalii** 2024-07-06 22:55 UTC
Labels: bug, help wanted
